{
 "title": "Wurm",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(wurm_ticks_total,job)"
    }
   },
   {
    "name": "Server",
    "query": {
     "query": "label_values(wurm_ticks_total{job=\"$job\"},server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Creatures",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "wurm_creatures{server=\"$Server\", job=\"$job\"}",
     "legendFormat": "Creatures"
    }
   ]
  },
  {
   "title": "Items",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "wurm_items{server=\"$Server\", job=\"$job\"}",
     "legendFormat": "Items"
    }
   ]
  },
  {
   "title": "Players",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "wurm_players{server=\"$Server\", job=\"$job\"}",
     "legendFormat": "Players"
    }
   ]
  },
  {
   "title": "Average Tick Breakdown",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by(part) (rate(wurm_tick_part_seconds_total{server=\"$Server\", job=\"$job\"}[30s]))",
     "legendFormat": "{{part}}"
    },
    {
     "expr": "sum(rate(wurm_tick_full_seconds_total{server=\"$Server\", job=\"$job\"}[30s])) - sum(rate(wurm_tick_part_seconds_total{server=\"$Server\", job=\"$job\"}[30s]))",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "Tick Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "TPS" } },
   "targets": [
    {
     "expr": "rate(wurm_ticks_total{server=\"$Server\", job=\"$job\"}[30s])",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Tick Time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(part) (rate(wurm_tick_part_seconds_total{server=\"$Server\", job=\"$job\"}[30s]))",
     "legendFormat": "{{part}}"
    },
    {
     "expr": "sum(rate(wurm_tick_full_seconds_total{server=\"$Server\", job=\"$job\"}[30s])) - sum(rate(wurm_tick_part_seconds_total{server=\"$Server\", job=\"$job\"}[30s]))",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "wurm_heap_max{server=\"$Server\", job=\"$job\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "wurm_heap_allocated{server=\"$Server\", job=\"$job\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "wurm_heap_used{server=\"$Server\", job=\"$job\"}",
     "legendFormat": "Used"
    }
   ]
  }
 ]
}